### ISSUE TITLE
Could not find ROS master. Either start a 'roscore' or abort loading the plugin.

### ISSUE THREAD

**Issue by machillest** [emiliofidalgo/bimos#6]
Hi
Thanks for your shared code. I did all steps, exactly same as explained here. with the same version of Ubuntu and ROS. I did test obindex as well. But after all steps, when I run rqt and import bimos it says:
Could not find ROS master. Either start a 'roscore' or abort loading the plugin.
Could you please help me about that.
Best,
Babaie

**Comment by emiliofidalgo** [comment]
Hi @machillest 
Are you executing the graphical interface in a different machine where you execute Bimos? It seems that it is a problem related with your ROS configuration, since your rqt is not able to find a roscore. Please, check the value of the ROS_MASTER_URI and ROS_IP environment variables.

Another idea: make sure you are using the same branch on obindex and BIMOS.

Please, let me know your progress.

Best,

**Comment by GIT862** [comment]
i have the same problem.through ssh connect robot running rviz showing ' could not find ros master .either start a roscore or abort loading the plugin.

**Comment by emiliofidalgo** [comment]
Hi @GIT862,

Did you try the steps I mentioned? It is a problem related with your ROS configuration:

http://wiki.ros.org/ROS/NetworkSetup

I hope this helps,
