### ISSUE TITLE
blending takes a lot of time 

### ISSUE THREAD

**Issue by MerlotQ** [emiliofidalgo/bimos#7]
The result shows that blending costs a lot more time than optimization and feature extraction and matching.  What is the main cause of this?

**Comment by emiliofidalgo** [comment]
Hi!

As commented in the paper, the blending step is an adaptation of the OpenCV _stitching_ module to be used in Bimos. We do not know exactly full details of the process, but note that it performs several computational expensive operations at image level like seam search, exposure compensation, multi-band blending, an so on. Therefore, it is normal that this step is the slowest one.

In Bimos, you can disable the blend_seams options to speed up this process. The resulting mosaic won't be visually good, since you are not performing the complete blending step, but this can help to see if the result is topologically coherent.
